######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 18 10:13:46 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              Application \
              FieldsDefinition \
              GlobalFunctions \
              InitialCondition \
              Simulation \
              Application/ColoringSchemeClass \
              Application/QCustomPlot \
              Solvers/OneDimensional \
              Solvers/TwoDimensional \
              Solvers/OneDimensional/FluxSolvers \
              Solvers/TwoDimensional/FluxSolvers
INCLUDEPATH += . \
               Application \
               FieldsDefinition \
               GlobalFunctions \
               Simulation \
               Solvers/TwoDimensional \
               Solvers/TwoDimensional/FluxSolvers \
               Application/QCustomPlot \
               Application/ColoringSchemeClass \
               InitialCondition \
               Solvers/OneDimensional \
               Solvers/OneDimensional/FluxSolvers

# Input
HEADERS += constants.h \
           Application/Plot1D.h \
           Application/Plot2D.h \
           Application/SimulationMainWindow.h \
           Application/SimulationMainWindow1D.h \
           Application/SimulationMainWindow2D.h \
           Application/ui_mainwindow.h \
           Application/ui_Plot2DWindow.h \
           FieldsDefinition/Field1DClass.h \
           FieldsDefinition/Field2DClass.h \
           GlobalFunctions/intInput.h \
           GlobalFunctions/saveDataIntoFile.h \
           GlobalFunctions/saveImageIntoFile.h \
           GlobalFunctions/solveTridiagonalMatrix.h \
           InitialCondition/InitialConditionClass.h \
           InitialCondition/InitialConditionClass_RndNoise.h \
           InitialCondition/InitialConditionClass_Sin.h \
           InitialCondition/InitialConditionClass_Step.h \
           Simulation/Simulation1DClass.h \
           Simulation/Simulation2DClass.h \
           Application/ColoringSchemeClass/ColoringSchemeClass.h \
           Application/ColoringSchemeClass/ColoringSchemeClassBlue.h \
           Application/ColoringSchemeClass/ColoringSchemeClassBW.h \
           Application/ColoringSchemeClass/ColoringSchemeClassHot.h \
           Application/ColoringSchemeClass/ColoringSchemeClassX.h \
           Application/QCustomPlot/qcustomplot.h \
           Solvers/OneDimensional/ForwardEulerScheme.h \
           Solvers/OneDimensional/KurganovTadmor2000Scheme.h \
           Solvers/OneDimensional/KurganovTadmor2ndOrder2000Scheme.h \
           Solvers/OneDimensional/LaxFriedrichsScheme.h \
           Solvers/OneDimensional/MacCormackScheme.h \
           Solvers/OneDimensional/MainSolverClass.h \
           Solvers/OneDimensional/RK4KurganovTadmor2000Scheme.h \
           Solvers/OneDimensional/RK4Scheme.h \
           Solvers/TwoDimensional/ForwardEulerScheme2D.h \
           Solvers/TwoDimensional/LaxFriedrichsScheme2D.h \
           Solvers/TwoDimensional/MainSolverClass2D.h \
           Solvers/TwoDimensional/RK4Scheme2D.h \
           Solvers/OneDimensional/FluxSolvers/FluxCalculatorClass.h \
           Solvers/OneDimensional/FluxSolvers/FluxCalculatorClassLinearReconstructionScheme.h \
           Solvers/OneDimensional/FluxSolvers/FluxCalculatorClassMUSCLScheme.h \
           Solvers/OneDimensional/FluxSolvers/FluxCalculatorPiecewiseParabolicReconstructionScheme.h \
           Solvers/TwoDimensional/FluxSolvers/FluxCalculatorClass2D.h \
           Solvers/TwoDimensional/FluxSolvers/FluxCalculatorClassLinearReconstructionScheme2D.h
SOURCES += main.cpp \
           Application/Plot1D.cpp \
           Application/Plot2D.cpp \
           Application/SimulationMainWindow.cpp \
           Application/SimulationMainWindow1D.cpp \
           Application/SimulationMainWindow2D.cpp \
           FieldsDefinition/Field1DClass.cpp \
           FieldsDefinition/Field2DClass.cpp \
           GlobalFunctions/intInput.cpp \
           GlobalFunctions/saveDataIntoFile.cpp \
           GlobalFunctions/saveImageIntoFile.cpp \
           GlobalFunctions/solveTridiagonalMatrix.cpp \
           InitialCondition/InitialConditionClass_RndNoise.cpp \
           InitialCondition/InitialConditionClass_Sin.cpp \
           InitialCondition/InitialConditionClass_Step.cpp \
           Simulation/Simulation1DClass.cpp \
           Simulation/Simulation2DClass.cpp \
           Application/ColoringSchemeClass/ColoringSchemeClassBlue.cpp \
           Application/ColoringSchemeClass/ColoringSchemeClassBW.cpp \
           Application/ColoringSchemeClass/ColoringSchemeClassHot.cpp \
           Application/ColoringSchemeClass/ColoringSchemeClassX.cpp \
           Application/QCustomPlot/qcustomplot.cpp \
           Solvers/OneDimensional/ForwardEulerScheme.cpp \
           Solvers/OneDimensional/KurganovTadmor2000Scheme.cpp \
           Solvers/OneDimensional/KurganovTadmor2ndOrder2000Scheme.cpp \
           Solvers/OneDimensional/LaxFriedrichsScheme.cpp \
           Solvers/OneDimensional/MacCormackScheme.cpp \
           Solvers/OneDimensional/RK4KurganovTadmor2000Scheme.cpp \
           Solvers/OneDimensional/RK4Scheme.cpp \
           Solvers/TwoDimensional/ForwardEulerScheme2D.cpp \
           Solvers/TwoDimensional/LaxFriedrichsScheme2D.cpp \
           Solvers/TwoDimensional/RK4Scheme2D.cpp \
           Solvers/OneDimensional/FluxSolvers/FluxCalculatorClassLinearReconstructionScheme.cpp \
           Solvers/OneDimensional/FluxSolvers/FluxCalculatorClassMUSCLScheme.cpp \
           Solvers/OneDimensional/FluxSolvers/FluxCalculatorPiecewiseParabolicReconstructionScheme.cpp \
           Solvers/TwoDimensional/FluxSolvers/FluxCalculatorClassLinearReconstructionScheme2D.cpp
